package com.dpdocter.enums;

public enum AnalyticType {
	LEADS_SOURCE("LEADS_SOURCE"), GENDER("GENDER"), LEAD_STAGE("LEAD_STAGE"), LEADS_TYPE("LEADS_TYPE"),
	TREATMENT("TREATMENT"), FOLLOWUP("FOLLOWUP"), AVG_TIME("AVG_TIME"), COST("COST"), LANGUAGE("LANGUAGE"),
	CREATED_FROM("CREATED_FROM"), CLINIC("CLINIC"), DOCTOR("DOCTOR"), CONTACT_STATE("CONTACT_STATE"),
	CANCELLED_BY("CANCELLED_BY"), RESCHEDULED_BY("RESCHEDULED_BY"), APPOINTMENT_TYPE("APPOINTMENT_TYPE"),
	APPOINTMENT_FOR("APPOINTMENT_FOR"), APPOINTMENT_BY("APPOINTMENT_BY"), APPOINTMENT_STATE("APPOINTMENT_STATE"),
	CREATED_BY("CREATED_BY"), APPOINTMENT_STATUS("APPOINTMENT_STATUS"), LEADS("LEADS"), APPOINTMENT("APPOINTMENT"),
	AMOUNT_SPEND("AMOUNT_SPEND"), REACH("REACH"), GENUINE_LEAD("GENUINE_LEAD"), HOT_LEAD("HOT_LEAD"),
	CONVERTED("CONVERTED"), COST_PER_CLICK("COST_PER_CLICK"), NOT_INTERESTED("NOT_INTERESTED"), FUNNEL("FUNNEL"),
	DENTAL_CLINICS("DENTAL_CLINICS");

	private String type;

	public String getType() {
		return type;
	}

	private AnalyticType(String type) {
		this.type = type;
	}

}
