package com.dpdocter.enums;

public enum ComponentType {

	CLINICAL_NOTES("CLINICAL_NOTES"), REPORTS("REPORTS"), PRESCRIPTIONS("PRESCRIPTIONS"), ALL("ALL"), BILING(
			"BILING"), VISITS("VISITS"), PATIENT("PATIENT"), DOCTOR("DOCTOR"), BROADCAST("BROADCAST") ,ORDER_PLACED("ORDER_PLACED"),ORDER_CONFIRMED(
					"ORDER_CONFIRMED"),  ORDER_PICKED_UP(
							"ORDER_PICKED_UP"), ORDER_DISPATCHED(
									"ORDER_DISPATCHED"), ORDER_PACKED("ORDER_PACKED"), ORDER_OUT_FOR_DELIVERY("ORDER_OUT_FOR_DELIVERY"), ORDER_DELIVERED("ORDER_DELIVERED"),
	DOCTOR_ACTIVATION("DOCTOR_ACTIVATION"),PACKAGE_DETAIL("PACKAGE_DETAIL"),COMPANY_ACTIVATION("COMPANY_ACTIVATION"),ONLINE_CONSULTATION("ONLINE_CONSULTATION"),APPOINTMENT_REFRESH("APPOINTMENT_REFRESH"),
	DOCTOR_LAB_REPORTS("DOCTOR_LAB_REPORTS"),APPOINTMENT("APPOINTMENT"),TREATMENTS_REFRESH("TREATMENTS_REFRESH"),PATIENT_REFRESH("PATIENT_REFRESH"), EMAIL_VERIFICATION("EMAIL_VERIFICATION"), SIGNED_UP("SIGNED_UP"), REFRESH_VACCINATION("REFRESH_VACCINATION"), REFRESH_GROWTH_CHART("REFRESH_GROWTH_CHART"), REFRESH_BABY_ACHIEVEMENTS("REFRESH_BABY_ACHIEVEMENTS"), CALENDAR_REMINDER("CALENDAR_REMINDER"), 
	USER_RECORD("USER_RECORD"), REFRESH_DOCTOR_LAB_REPORTS("REFRESH_DOCTOR_LAB_REPORTS"), EVENT("EVENT"), PRESCRIPTION_REFRESH("PRESCRIPTION_REFRESH"), PATIENT_VISIT_REFRESH("PATIENT_VISIT_REFRESH"),
	DENTAL_WORKS("DENTAL_WORKS"), DENTAL_IMAGING_REQUEST("DENTAL_IMAGING_REQUEST"), RECEIPT_REFRESH("RECEIPT_REFRESH"), DISCHARGE_SUMMARY_REFRESH("DISCHARGE_SUMMARY_REFRESH"), DENTAL_WORK_REFRESH("DENTAL_WORK_REFRESH"),
	REFRESH_DENTAL_IMAGING("REFRESH_DENTAL_IMAGING"), CLINICAL_NOTES_REFRESH("CLINICAL_NOTES_REFRESH"), RECORDS_REFRESH("RECORDS_REFRESH"), INVOICE_REFRESH("INVOICE_REFRESH"), APPOINTMENT_STATUS_CHANGE("APPOINTMENT_STATUS_CHANGE"), DEACTIVATED("DEACTIVATED");

	private String type;

	private ComponentType(String type) {
		this.type = type;
	}

	public String getType() {
		return type;
	}

}
