package com.dpdocter.enums;

public enum ContactState {
	SCHEDULED("SCHEDULED"), VISITED("VISITED"), CONVERTED("CONVERTED"), TREATMENT_ONGOING("TREATMENT_ONGOING"),
	TREATMENT_FINISH("TREATMENT_FINISH"), FOLLOWUP("FOLLOWUP"), TREATMENT_NOT_STARTED("TREATMENT_NOT_STARTED"),
	CONSULTATION_DONE("CONSULTATION_DONE"), FIRSTCALL("FIRSTCALL"), SECONDCALL("FIRSTCALL"), THIRDCALL("FIRSTCALL"),
	FIRSTAPPOINTMENT("FIRSTAPPOINTMENT");

	String state;

	public String getState() {
		return state;
	}

	private ContactState(String state) {
		this.state = state;
	}
}
