package com.dpdocter.enums;

public enum Resource {
	COMPLAINT("COMPLAINT"), OBSERVATION("OBSERVATION"), INVESTIGATION("INVESTIGATION"), DIAGNOSIS("DIAGNOSIS"),
	NOTES("NOTES"), DIAGRAM("DIAGRAM"), PATIENT("PATIENT"), DRUG("DRUG"), LABTEST("LABTEST"), COUNTRY("COUNTRY"),
	STATE("STATE"), CITY("CITY"), LANDMARKLOCALITY("LANDMARKLOCALITY"), DOCTOR("DOCTOR"), LOCATION("LOCATION"),
	DIAGNOSTICTEST("DIAGNOSTICTEST"), REFERENCE("REFERENCE"), DISEASE("DISEASE"), DRUGSDRUGTYPE("DRUGSDRUGTYPE"),
	DOCTORDRUG("DOCTORDRUG"), PRESENT_COMPLAINT("PRESENT_COMPLAINT"), PROVISIONAL_DIAGNOSIS("PROVISIONAL_DIAGNOSIS"),
	GENERAL_EXAMINATION("GENERAL_EXAMINATION"), SYSTEMIC_EXAMINATION("SYSTEMIC_EXAMINATION"),
	HISTORY_OF_PRESENT_COMPLAINT("HISTORY_OF_PRESENT_COMPLAINT"), MENSTRUAL_HISTORY("MENSTRUAL_HISTORY"),
	OBSTETRIC_HISTORY("OBSTETRIC_HISTORY"), INDICATION_OF_USG("INDICATION_OF_USG"),
	TREATMENTSERVICE("TREATMENTSERVICE"), PA("PA"), PV("PV"), PS("PS"), ECG("ECG"), XRAY("XRAY"), ECHO("ECHO"),
	HOLTER("HOLTER"), PHARMACY("PHARMACY"), COLLECTION_BOY("COLLECTION_BOY"), PROCEDURE_NOTE("PROCEDURE_NOTE"),
	PC_NOSE("PC_NOSE"), PC_EARS("PC_EARS"), PC_THROAT("PC_THROAT"), PC_ORAL_CAVITY("PC_ORAL_CAVITY"),
	NOSE_EXAM("NOSE_EXAM"), NECK_EXAM("NECK_EXAM"), EARS_EXAM("EARS_EXAM"),
	ORAL_CAVITY_THROAT_EXAM("ORAL_CAVITY_THROAT_EXAM"), INDIRECT_LARYGOSCOPY_EXAM("INDIRECT_LARYGOSCOPY_EXAM"),
	MEDICAL_COUNCIL("MEDICAL_COUNCIL"), INSTITUDE("INSTITUDE"), QAULIFICATION("QAULIFICATION"),
	SPECIALITY("SPECIALITY"), PROFESSIONAL_MEMBERSHIP("PROFESSIONAL_MEMBERSHIP"), DENTAL_WORKS("DENTAL_WORKS"),
	NUTRIENT("NUTRIENT"), INGREDIENT("INGREDIENT"), RECIPE("RECIPE"), EXERCISE("EXERCISE"),
	EXPENSE_TYPE("EXPENSE_TYPE"), OFFER("OFFER"), SERVICE("SERVICE"), TRENDING("TRENDING");

	private String type;

	private Resource(String type) {
		this.type = type;
	}

	public String getType() {
		return type;
	}

}
