package com.dpdocter.enums;

public enum YogaTypeEnum {

	HOT_YOGA("HOT_YOGA"),POWER_YOGA("POWER_YOGA"),PRAGYA_YOGA("PRAGYA_YOGA"),TIBETAN_YOGA("TIBETAN_YOGA"),PADDLE_BOAT_YOGA("PADDLE_BOAT_YOGA"),AERIAL_YOGA("AERIAL_YOGA"),
	HATHA_YOGA("HATHA_YOGA"),BRICK_YOGA("BRICK_YOGA"),YIN_YOGA("YIN_YOGA"),VINYASA_YOGA("VINYASA_YOGA"),SCULPT_YOGA("SCULPT_YOGA"),SATYANANDA_YOGA("SATYANANDA_YOGA"),
	AQUA_YOGA("AQUA_YOGA"),ASHTANGA_YOGA("ASHTANGA_YOGA"),DANDA_YOGA("DANDA_YOGA"),BASKET_BALL("BASKET_BALL"),STRAP_YOGA("STRAP_YOGA"),WALL_YOGA("WALL_YOGA"),
	INSIGHT_YOGA("INSIGHT_YOGA"),QUANTUM_YOGA("QUANTUM_YOGA"),ALIGNMENT_YOGA("ALIGNMENT_YOGA"),ANANDA_YOGA("ANANDA_YOGA"),CORE_STRENGTH_FLOW("CORE_STRENGHT_FLOW"),
	LUNAR_PHASE_FLOW("LUNAR_PHASE_FLOW"),SIVANANDA_YOGA("SIVANANDA_YOGA");
	
		private String type;

		private YogaTypeEnum(String type) {
			this.type = type;
		}

		public String getType() {
			return type;
		}
		
		
}
